"""delivery keeps its provider and payload

Revision ID: 1f83673e3596
Revises: 682869bada6e
Create Date: 2026-07-27 10:19:11.237838
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1f83673e3596'
down_revision: str | None = '682869bada6e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        # server_default matters: without it these NOT NULL columns cannot be added to a table
        # that already has rows, and an upgrade that only works on an empty database is not an
        # upgrade. Existing deliveries were all GlitchTip and their bodies are gone.
        batch_op.add_column(
            sa.Column('provider', sa.String(length=20), nullable=False,
                      server_default='glitchtip')
        )
        batch_op.add_column(
            sa.Column('payload_json', sa.Text(), nullable=False, server_default='{}')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('payload_json')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
