"""initial schema

Revision ID: 682869bada6e
Revises: 
Create Date: 2026-07-26 20:15:06.382386
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '682869bada6e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('forge', sa.String(length=20), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=False),
    sa.Column('webhook_secret_hash', sa.String(length=128), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('manifest_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('provider_delivery_id', sa.String(length=200), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'provider_delivery_id', 'payload_hash', name='uq_delivery')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_received_at'), ['received_at'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Enum('new', 'triaged', 'waiting-approval', 'ready', 'in-progress', 'pr-open', 'done', 'failed', 'not-reproducible', 'human-only', 'reopened', name='item_state', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('lane', sa.Enum('green', 'amber', 'red', name='lane', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('kind', sa.Enum('bug', 'other', name='item_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('lane_reason', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forge_issue_ref', sa.String(length=100), nullable=True),
    sa.Column('regression', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'fingerprint', name='uq_item_fingerprint')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_project_id'), ['project_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('fingerprint_derived', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('culprit', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_events_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_events_delivery_id'))

    op.drop_table('events')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_project_id'))

    op.drop_table('items')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_received_at'))
        batch_op.drop_index(batch_op.f('ix_deliveries_project_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))

    op.drop_table('projects')
    # ### end Alembic commands ###
