"""Webhook tokens: generation, storage and comparison.

Shared by the CLI that issues them and the receiver that checks them, so there is exactly one
opinion about how they work.

**Why a plain SHA-256 and not bcrypt or argon2.** Those exist to slow brute force against
*human-chosen* secrets, drawn from a tiny space. These tokens are 32 random bytes generated by us:
the search space is 2^256 and hashing speed helps an attacker not at all. Paying a KDF's cost per
inbound webhook would buy nothing and slow the front door, which is the one place where latency
turns into lost deliveries.
"""

import hashlib
import hmac
import secrets

#: 32 bytes of entropy, url-safe. Long enough that guessing is not a threat model, short enough that
#: the resulting webhook URL is still something a person can paste without wrapping.
TOKEN_BYTES = 32


def generate_token() -> str:
    """A new webhook token.

    Never chosen by a user: a secret picked by hand is a secret that can be guessed.
    """
    return secrets.token_urlsafe(TOKEN_BYTES)


def hash_token(token: str) -> str:
    """What gets stored. The token itself is shown once and never persisted."""
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def verify_token(token: str, expected_hash: str) -> bool:
    """Constant-time comparison.

    `==` on the hashes would leak, through timing, how much of a guess was right — which is exactly
    the feedback an attacker needs to find the rest one character at a time.
    """
    return hmac.compare_digest(hash_token(token), expected_hash)
